ALTER TABLE t_p22534578_messenger_mobile_app.chats
  ADD COLUMN IF NOT EXISTS is_channel BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS avatar_url TEXT,
  ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT FALSE;

ALTER TABLE t_p22534578_messenger_mobile_app.chat_members
  ADD COLUMN IF NOT EXISTS can_post BOOLEAN DEFAULT FALSE;
